[project]
name = "thesis-function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.80.0",
    "pydantic>=2.12.4",
]
